### ISSUE TITLE
Project initialization(Group task)- /1H/

### ISSUE THREAD

**Issue by Hasinarahman** [Hasinarahman/space-travelers-hub#1]
1. **Initalize React Project 
- ** Description:** Setup a new React project using 'create-react-app' install and contigure the necessary dependencies like Redux, React, Router, and TailwindCSS.
- pighla Hasina Rahmani: [Rockets]
- Najeeba Qarqin: [Misssion]
- Hasina rahmani and Najeeba Qarqin: [My profile]

**Comment by ahzamir** [comment]
@latifa-wakili 
@Najeeba-Qarqin 
@Hasinarahman 

- Well done team your tasks and Kanban Board are perfect and have been approved by me, just add some tasks for the mobile and desktop version designs for all components
